# Generated by Django 5.0.3 on 2024-03-20 10:15

import django.db.models.deletion
import tanks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=tanks.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanks_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TankSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks_bought', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks_sold', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank')),
            ],
        ),
        migrations.CreateModel(
            name='TankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks_sent', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
