# Generated by Django 5.0.3 on 2024-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_alter_tanksale_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
